In [1]:
]add Statistics

    Updating registry at `/srv/julia/pkg/registries/General.toml`
   Resolving package versions...
  No Changes to `~/Project.toml`
  No Changes to `~/Manifest.toml`


In [2]:
using Statistics: mean

In [3]:
moving_average(vs,n) = [sum(@view vs[i:(i+n-1)])/n for i in 1:(length(vs)-(n-1))]

moving_average (generic function with 1 method)

In [4]:
weighted_sum(m, n) = sum([i*m[i] for i in 1:n])

weighted_sum (generic function with 1 method)

In [5]:
weighted_moving_average(vs,n) = [weighted_sum(vs[i:(i+n-1)], n)/sum(1:n) for i in 1:(length(vs)-(n-1))]

weighted_moving_average (generic function with 1 method)

In [6]:
X = [120, 110, 130, 120, 180, 240, 160]

7-element Vector{Int64}:
 120
 110
 130
 120
 180
 240
 160

# weighted_moving_average(X, 4)

In [7]:
function ema(A, alpha)
    # fast exponential moving average: X - moving average, A - data,
    # alpha - exponential forgetting parameter
    n = length(A)
    X = zeros(n+1) # Declare X
    beta = 1-alpha
    X[1] = A[1]
    for k = 2:n+1
        X[k] = X[k-1] + alpha*(A[k-1] - X[k-1])
    end
    return X
end

ema (generic function with 1 method)

In [8]:
X = [30, 25, 35, 25, 20, 30, 35, 40, 30, 45, 20]

11-element Vector{Int64}:
 30
 25
 35
 25
 20
 30
 35
 40
 30
 45
 20

In [9]:
ema(X, 0.3)

12-element Vector{Float64}:
 30.0
 30.0
 28.5
 30.45
 28.814999999999998
 26.170499999999997
 27.319349999999996
 29.623544999999996
 32.7364815
 31.915537049999998
 35.840875935
 31.0886131545

In [85]:
X = [5, 7, 15, 22, 27, 36]
Y = [28, 40, 65, 180, 96, 130]

6-element Vector{Int64}:
  28
  40
  65
 180
  96
 130

In [91]:
s_X = sum(X)

112

In [92]:
s_Y = sum(Y)

539

In [93]:
s_XY = sum(X.*Y)

12627

In [94]:
sum(X.^2)

2808

In [95]:
b = ((length(X) .* s_XY) - (s_X*s_Y))/(sum(X.^2)*(length(X)-1))

1.0964387464387464

In [96]:
a = (sum(Y) - b.*sum(X))/length(X)

69.3664767331434